services:
  zipkin:
    container_name: zipkin
    build:
      context: ./zipkin-service
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
    environment:
      LOGGING_LEVEL_ZIPKIN2: DEBUG
      LOGGING_LEVEL_ROOT: DEBUG
    networks:
      - zipkin-net

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
    ports:
      - "8081:8081"
    environment:
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
    networks:
      - zipkin-net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      PAYMENT_SERVICE_URL: http://payment-service:8081
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - payment-service
    networks:
      - zipkin-net

networks:
  zipkin-net:
    driver: bridge
